export const TOPICS = [
    "ancient world",
    "animals",
    "art",
    "brain",
    "clothes",
    "colours",
    "Common phrases",
    "Daily routines",
    "different",
    "earth",
    "Emotions",
    "entertainment",
    "family",
    "food",
    "Gardening",
    "history",
    "hobbies",
    "holidays",
    "Household items",
    "humans",
    "ideas",
    "inventions",
    "internet",
    "island",
    "language",
    "letters",
    "Leisure activities",
    "marine life",
    "movies",
    "music",
    "Music genres",
    "Mythology and legends",
    "natural world",
    "people",
    "places",
    "planets",
    "plants",
    "professions",
    "school",
    "space",
    "sports",
    "Technology ",
    "transportation",
    "travel",
    "underwater",
    "verbs and adjectives",
    "water",
    "weather",
    "wildlife",
]
