export const TOPICS = [
  "Adventure and Exploration",
  "Agriculture and Farming",
  "Architecture",
  "Astronomy",
  "Books and Literature",
  "Cities and Urban Life",
  "Cultural Traditions",
  "Economics and Business",
  "Education",
  "Engineering",
  "Environment and Conservation",
  "Food and Drink",
  "Geography",
  "Health and Wellness",
  "History and Archaeology",
  "Innovation",
  "Languages and Dialects",
  "Mythology",
  "Philosophy and Ethics",
  "Politics and Government",
  "Psychology and Behavior",
  "Spirituality",
  "Science and Technology",
  "Space Exploration",
  "Theater and Performing Arts",
  "Tourism and Hospitality",
  "Transportation and Vehicles",
  "Urban Planning",
  "Virtual Reality and Gaming",
  "Personal Development",
  "Public Health",
  "Renewable Energy",
  "Science Fiction",
  "Sociology",
  "Space Science",
  "Sustainability",
  "Traditional Crafts",
  "Virtual Worlds",
  "Marine Conservation",
  "Mathematics",
  "Family Dynamics",
  "Agriculture",
  "Astronomy and Cosmology",
  "Cultural Heritage",
  "Design and Innovation",
  "Digital Media",
  "Artificial Intelligence",
  "Digital Art",
  "Food Science",
  "Genetics",
  "Internet Security",
  "Marine Biology",
  "Neuroscience",
  "Philanthropy",
  "Robotics",
  "Space Travel",
  "Sports Science",
  "Technology Trends",
  "ancient world",
  "animals",
  "art",
  "brain",
  "clothes",
  "colours",
  "Common phrases",
  "Daily routines",
  "different",
  "earth",
  "Emotions",
  "entertainment",
  "family",
  "food",
  "Gardening",
  "history",
  "hobbies",
  "holidays",
  "Household items",
  "humans",
  "ideas",
  "inventions",
  "internet",
  "island",
  "language",
  "letters",
  "Leisure activities",
  "marine life",
  "movies",
  "music",
  "Music genres",
  "Mythology and legends",
  "natural world",
  "people",
  "places",
  "planets",
  "plants",
  "professions",
  "school",
  "space",
  "sports",
  "Technology ",
  "transportation",
  "travel",
  "underwater",
  "verbs and adjectives",
  "water",
  "weather",
  "wildlife",
]
